config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :accounts do
    get :fetch, :on => :collection
  end

  resources :expenses
  resources :expense_receipts
  resources :amazon_statements, only: [:index, :show] do
    get :fetch, :on => :collection
    collection do
      get :authenticate
      get :oauth_callback
    end
  end

  resources :sales_receipts
  resources :credentials
  get 'inventory/index'

  resources :adjustments
  resources :adjustment_types
  resources :sales
  resources :payments
  root 'home#index'

  resources :order_items

  resources :products do
    get :fetch, :on => :collection
  end

  resources :orders

  resources :contacts do
    get :fetch, :on => :collection
  end
  resources :inventory, only: [:index]
  resources :configs, only: [:index] do
    collection do
      put :change
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>It's Ridic! PIM</h1>
<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Amazon Credentials</h3>
      </div>
      <div class="panel-body">
        <%= link_to credentials_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-cog"> Amazon Credentials</i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Configuration Questions</h3>
      </div>
      <div class="panel-body">
        <%= link_to configs_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-cog"> Configuration Questions</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Amazon Settlements - Create Sales and Expense Receipts in QBO From Amazon</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to amazon_statements_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-dashboard"> Amazon Settlements</i>
        <% end %>
      </div> 
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Accounts</h3>
      </div>
      <div class="panel-body">
        <%= link_to accounts_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-cog"> Accounts</i>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Contacts</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_contact_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-user"> Add Contact</i>
        <% end %>
        <%= link_to contacts_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-user">View Contacts</i>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Products</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_product_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-barcode"> Add Product</i>
        <% end %>
        <%= link_to products_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-barcode"> View Products</i>
        <% end %>
      </div> 
    </div>
  </div>
  <div class="col-md-4">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Orders</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_order_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-list-alt"> Add Order</i>
        <% end %>
        <%= link_to orders_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-list-alt"> View Orders</i>
        <% end %>
      </div> 
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Payment Types</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_payment_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-usd"> Add Payment Type</i>
        <% end %>
      </div> 
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Adjustment Types</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_adjustment_type_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-erase"> Add Adjustment Type</i>
        <% end %>
      </div> 
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Sales</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_sales_receipt_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-shopping-cart"> Add Sale</i>
        <% end %>
        <%= link_to sales_receipts_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-shopping-cart">  View Sales</i>
        <% end %>
      </div> 
    </div>
  </div>
  <div class="col-md-6">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Adjustments</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to new_adjustment_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-scale"> Add Adjustment</i>
        <% end %>
        <%= link_to adjustments_path, class: "btn btn-primary" do %>
          <i class="glyphicon glyphicon-scale"> View Adjustments</i>
        <% end %>
      </div> 
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12">
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h3 class="panel-title">Inventory</h3> 
      </div> 
      <div class="panel-body">
        <%= link_to inventory_index_path, class: "btn btn-warning" do %>
          <i class="glyphicon glyphicon-dashboard"> Inventory</i>
        <% end %>
      </div> 
    </div>
  </div>
</div>