config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :accounts do
    get :fetch, :on => :collection
  end

  resources :expenses
  resources :expense_receipts
  resources :amazon_statements, only: [:index, :show] do
    get :fetch, :on => :collection
    collection do
      get :authenticate
      get :oauth_callback
    end
  end

  resources :sales_receipts
  resources :credentials
  get 'inventory/index'

  resources :adjustments
  resources :adjustment_types
  resources :sales
  resources :payments
  root 'home#index'

  resources :order_items

  resources :products do
    get :fetch, :on => :collection
  end

  resources :orders

  resources :contacts do
    get :fetch, :on => :collection
  end
  resources :inventory, only: [:index]
  resources :configs, only: [:index] do
    collection do
      put :change
    end
  end
end

app/models/expense_receipt.rb
class ExpenseReceipt < ActiveRecord::Base
  belongs_to :account
  has_many :expenses, dependent: :destroy
  accepts_nested_attributes_for :expenses, reject_if: :all_blank, allow_destroy: true
end

app/controllers/expense_receipts_controller.rb
class ExpenseReceiptsController < ApplicationController
  before_action :set_expense_receipt, only: [:show, :edit, :update, :destroy]

  # GET /expense_receipts
  # GET /expense_receipts.json
  def index
    @expense_receipts = ExpenseReceipt.all
  end

  # GET /expense_receipts/1
  # GET /expense_receipts/1.json
  def show
  end

  # GET /expense_receipts/new
  def new
    @expense_receipt = ExpenseReceipt.new
  end

  # GET /expense_receipts/1/edit
  def edit
  end

  # POST /expense_receipts
  # POST /expense_receipts.json
  def create
    @expense_receipt = ExpenseReceipt.new(expense_receipt_params)

    respond_to do |format|
      if @expense_receipt.save
        format.html { redirect_to @expense_receipt, notice: 'Expense receipt was successfully created.' }
        format.json { render :show, status: :created, location: @expense_receipt }
      else
        format.html { render :new }
        format.json { render json: @expense_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expense_receipts/1
  # PATCH/PUT /expense_receipts/1.json
  def update
    respond_to do |format|
      if @expense_receipt.update(expense_receipt_params)
        format.html { redirect_to @expense_receipt, notice: 'Expense receipt was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense_receipt }
      else
        format.html { render :edit }
        format.json { render json: @expense_receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expense_receipts/1
  # DELETE /expense_receipts/1.json
  def destroy
    @expense_receipt.destroy
    respond_to do |format|
      format.html { redirect_to expense_receipts_url, notice: 'Expense receipt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense_receipt
      @expense_receipt = ExpenseReceipt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_receipt_params
      params.require(:expense_receipt).permit(:description)
    end
end

app/helpers/expense_receipts_helper.rb
module ExpenseReceiptsHelper
end

app/views/expense_receipts/_expense_fields.html.erb
<!--[:id, :quantity, :sales_receipt_id, :amount, :rate]) -->

<div class="container">
  <div class="nested-fields">
    <div class="row">
      <div class="col-md-3">
        <div class="form-group inline">
          <%= f.label :expense_account %>
          <%= f.collection_select :expense_account_id, ExpenseAccount.all, :id, :name, {}, { class: "form-control" } %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <%= f.label :amount %>
          <%= f.number_field :amount, class: "form-control" %>
        </div>
      </div>
      <div class="col-md-5">
        <br />
        <%= link_to_remove_association "X", f, class: "btn btn-warning", style: "margin-top: 0.5%;" %>
      </div>
    </div>
  </div>
</div>

app/views/expense_receipts/_form.html.erb
<%= simple_form_for(@expense_receipt, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.association :bank_account %>
  </div>

  <div class="form-group">
    <%= f.input :description %>
  </div>

  <h3>Expenses</h3>
  <div id="sale-items">
    <%= f.simple_fields_for :expenses do |expense| %>
      <%= render 'expense_fields', :f => expense %>
    <% end %>
    <div class="links" style="margin-top: 1%; margin-bottom: 1%;">
      <%= link_to_add_association 'add expense', f, :expenses, class: "btn btn-warning" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/expense_receipts/edit.html.erb
<h1>Editing Expense Receipt</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense_receipt %> |
<%= link_to 'Back', expense_receipts_path %>

app/views/expense_receipts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expense Receipts</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expense_receipts.each do |expense_receipt| %>
      <tr>
        <td><%= expense_receipt.description %></td>
        <td><%= link_to 'Show', expense_receipt %></td>
        <td><%= link_to 'Edit', edit_expense_receipt_path(expense_receipt) %></td>
        <td><%= link_to 'Destroy', expense_receipt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense receipt', new_expense_receipt_path %>

app/views/expense_receipts/new.html.erb
<h1>New Expense Receipt</h1>

<%= render 'form' %>

<%= link_to 'Back', expense_receipts_path %>

app/views/expense_receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @expense_receipt.description %>
</p>

<%= link_to 'Edit', edit_expense_receipt_path(@expense_receipt) %> |
<%= link_to 'Back', expense_receipts_path %>