config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :accounts do
    get :fetch, :on => :collection
  end

  resources :expenses
  resources :expense_receipts
  resources :amazon_statements, only: [:index, :show] do
    get :fetch, :on => :collection
    collection do
      get :authenticate
      get :oauth_callback
    end
  end

  resources :sales_receipts
  resources :credentials
  get 'inventory/index'

  resources :adjustments
  resources :adjustment_types
  resources :sales
  resources :payments
  root 'home#index'

  resources :order_items

  resources :products do
    get :fetch, :on => :collection
  end

  resources :orders

  resources :contacts do
    get :fetch, :on => :collection
  end
  resources :inventory, only: [:index]
  resources :configs, only: [:index] do
    collection do
      put :change
    end
  end
end

app/models/sale.rb
class Sale < ActiveRecord::Base
  belongs_to :product
  belongs_to :sales_receipt
  after_save :set_rate
  
  private

  def set_rate
    if self.rate.blank?
      self.update_column(:rate, amount.to_f / quantity.to_f)
    end
  end
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]

  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
  end

  # GET /sales/1/edit
  def edit
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:product_id, :payment_id, :contact_id, :sale_price, :quantity, :sale_average_cost, :user_date)
    end
end

app/helpers/sales_helper.rb
module SalesHelper
  def product_name(sale)
    if sale.product.nil?
      sale.description
    else
      sale.product.name || sale.description
    end
  end
end

app/views/sales/_form.html.erb
<%= simple_form_for(@sale, html: { class: "form-horizontal"} ) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= link_to "Add Date", "#", id: "adduserdate" %>
    <%= f.input :user_date, include_blank: true %>
    <%= f.association :product %>
    <%= f.association :payment %>
    <%= f.association :contact %>
    <%= f.input :quantity %>
    <%= f.input :sale_price %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1>Editing Sale</h1>

<%= render 'form' %>

<%= link_to 'Show', @sale %> |
<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sales</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Payment</th>
      <th>Contact</th>
      <th>Sale price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.product %></td>
        <td><%= sale.payment %></td>
        <td><%= sale.contact %></td>
        <td><%= sale.sale_price %></td>
        <td><%= link_to 'Show', sale %></td>
        <td><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sale', new_sale_path %>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @sale.product %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @sale.payment %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @sale.contact %>
</p>

<p>
  <strong>Sale price:</strong>
  <%= @sale.sale_price %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>